import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/components/layout/Header'
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

     <ClerkProvider>
    <html lang="en">
           <head>
           </head>
      <body className={inter.className}>
        <Header/>
        <main className='   py-16'>

        {children}
        
        </main>
        
        
        </body>
    </html>
    </ClerkProvider>
  )
}
